from .basemodel import *


class Noise_Temp(BaseModel):
    keyFacility = IntegerField()
    fkSub_Header = IntegerField()
    TS = TimestampField()
    DataSet = IntegerField()
    ChopStatus = IntegerField()
    FreqLO = DoubleField()
    CenterIF = DoubleField()
    BWIF = DoubleField()
    LOLock = IntegerField()
    TimedOut = IntegerField()
    TAmbient = FloatField()
    TColdLoad = FloatField()
    Pol0Sb1PHot = DoubleField()
    Pol0Sb1PHotStdErr = DoubleField()
    Pol0Sb1PCold = DoubleField()
    Pol0Sb1PColdStdErr = DoubleField()
    Pol0Sb1YFactor = DoubleField()
    Pol0Sb1YFactorStdErr = DoubleField()
    Pol0Sb2PHot = DoubleField()
    Pol0Sb2PHotStdErr = DoubleField()
    Pol0Sb2PCold = DoubleField()
    Pol0Sb2PColdStdErr = DoubleField()
    Pol0Sb2YFactor = DoubleField()
    Pol0Sb2YFactorStdErr = DoubleField()
    Pol1Sb1PHot = DoubleField()
    Pol1Sb1PHotStdErr = DoubleField()
    Pol1Sb1PCold = DoubleField()
    Pol1Sb1PColdStdErr = DoubleField()
    Pol1Sb1YFactor = DoubleField()
    Pol1Sb1YFactorStdErr = DoubleField()
    Pol1Sb2PHot = DoubleField()
    Pol1Sb2PHotStdErr = DoubleField()
    Pol1Sb2PCold = DoubleField()
    Pol1Sb2PColdStdErr = DoubleField()
    Pol1Sb2YFactor = DoubleField()
    Pol1Sb2YFactorStdErr = DoubleField()
    IFAtten01 = DoubleField()
    IFAtten02 = DoubleField()
    IFAtten11 = DoubleField()
    IFAtten12 = DoubleField()
    VJ_Pol0SIS1 = FloatField()
    VJ_Pol0SIS2 = FloatField()
    VJ_Pol1SIS1 = FloatField()
    VJ_Pol1SIS2 = FloatField()
    IJ_Pol0SIS1 = FloatField()
    IJ_Pol0SIS2 = FloatField()
    IJ_Pol1SIS1 = FloatField()
    IJ_Pol1SIS2 = FloatField()
    IMag_Pol0SIS1 = FloatField()
    IMag_Pol0SIS2 = FloatField()
    IMag_Pol1SIS1 = FloatField()
    IMag_Pol1SIS2 = FloatField()
    PAVD_Pol0 = FloatField()
    PAVD_Pol1 = FloatField()
    PAVG_Pol0 = FloatField()
    PAVG_Pol1 = FloatField()
    IsIncluded = IntegerField()

    class Meta:
        orm_mode = True
        db_table = 'Noise_Temp'
        primary_key = False
